name: ebay_motors
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  text_scroll: ^0.2.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.0
  flutter_animate: ^4.2.0+1
  animate_do: ^2.1.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf


